services:
  torch-gpu:
    profiles:
      - torch_gpu
    build:
      context: .
      dockerfile: containers/torch_env/Dockerfile
    image: torch-image
    container_name: torch_gpu
    volumes:
      - .:/workspace
    working_dir: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    stdin_open: true
    tty: true

  torch-cpu:
    profiles:
      - torch_cpu
    image: torch-image
    container_name: torch_cpu
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true

  jupyter:
      image: jupyter_torch
      profiles:
        - jupyter
      build:
        context: .
        dockerfile: containers/jupyter_env/Dockerfile
      container_name: jupyter_env
      volumes:
        - ./:/home/jacopo/work
      user: 'root'
      ports:
        - "8888:8888"
      environment:
        - ENABLE_JUPYTER_LAB=yes
        - JUPYTER_TOKEN=123
        - NB_USER=jacopo
        - CHOWN_HOME=yes
      working_dir: /home/jacopo

  chatbot:
    image: chatbot_image
    profiles:
      - chatbot
    build:
      context: .
      dockerfile: containers/chatbot/Dockerfile
    container_name: chatbot_container
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8890:8501"
    stdin_open: true
    tty: true